"""Compile the renderer's host shaders into embedded DXIL headers.

usage: python tools/gpu/compile_shaders.py [--dxc PATH]
Each src/gpu/shaders/<name>.hlsl with VsMain/PsMain entries becomes src/gpu/shaders/<name>_shaders.h.
"""
import argparse
import os
import subprocess
import sys
import tempfile

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..'))
SHADERS = os.path.join(ROOT, 'src', 'gpu', 'shaders')
DEFAULT_DXC = os.path.join(ROOT, 'tools', 'XenosRecomp', 'thirdparty', 'dxc-bin', 'bin', 'x64', 'dxc.exe')
ENTRIES = [('VsMain', 'vs_6_0', 'vs'), ('PsMain', 'ps_6_0', 'ps')]


def compile_one(dxc, src, entry, profile):
    with tempfile.TemporaryDirectory() as tmp:
        out = os.path.join(tmp, 'out.bin')
        args = [dxc, '-T', profile, '-E', entry, '-O3', src, '-Fo', out]
        subprocess.run(args, check=True)
        with open(out, 'rb') as fh:
            return fh.read()


def emit(name, blob):
    rows = [', '.join('0x%02x' % b for b in blob[i:i + 16]) for i in range(0, len(blob), 16)]
    return 'inline constexpr uint8_t %s[] = {\n  %s,\n};\n' % (name, ',\n  '.join(rows))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--dxc', default=DEFAULT_DXC)
    a = ap.parse_args()
    for file in sorted(os.listdir(SHADERS)):
        if not file.endswith('.hlsl'):
            continue
        stem = file[:-5]
        src = os.path.join(SHADERS, file)
        parts = ['// Generated by tools/gpu/compile_shaders.py from %s; do not edit.\n#pragma once\n\n#include <cstdint>\n\n'
                 'namespace ae::gpu::shaders {\n\n' % file]
        entries = ENTRIES if stem != 'resize' else [
            ('ColorMain', 'ps_6_0', 'color'), ('ColorMsMain', 'ps_6_0', 'color_ms'),
            ('DepthMain', 'ps_6_0', 'depth'), ('DepthMsMain', 'ps_6_0', 'depth_ms'),
            ('StencilMain', 'ps_6_0', 'stencil'), ('StencilMsMain', 'ps_6_0', 'stencil_ms')]
        for entry, profile, tag in entries:
            parts.append(emit('k%s_%s_dxil' % (stem.capitalize(), tag), compile_one(a.dxc, src, entry, profile)))
        parts.append('\n}  // namespace ae::gpu::shaders\n')
        with open(os.path.join(SHADERS, stem + '_shaders.h'), 'w', newline='\n') as fh:
            fh.write('\n'.join(parts))
        print('wrote ' + stem + '_shaders.h')
    return 0


if __name__ == '__main__':
    sys.exit(main())
